package model;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Entity class representing a Video Game in the system.
 * Contains information about the game including its name, release date,
 * platform, PEGI rating, and associations with user lists.
 *
 * @author ema
 */
@Entity
@Table(name = "videogame")
public class VideoGame implements Serializable {

    /**
     * Unique identifier for the video game.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "v_id")
    private int v_id;

    /**
     * Name of the video game.
     * Cannot be null and has a maximum length of 100 characters.
     */
    @Column(name = "v_name", nullable = false, length = 100)
    private String v_name;

    /**
     * Release date of the video game.
     */
    @Column(name = "v_release")
    private LocalDate v_release;

    /**
     * Gaming platform for which the game is designed.
     * Stored as an enumerated string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "v_platform")
    private Platform v_platform;

    /**
     * PEGI age rating for the video game.
     * Stored as an enumerated string value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "v_pegi")
    private Pegi v_pegi;

    /**
     * Set of listings that associate this video game with user profiles.
     * Represents the many-to-many relationship between games and user lists.
     */
    @OneToMany(mappedBy = "videogame", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Listed> listedInProfiles = new HashSet<>();

    /**
     * Default constructor for VideoGame.
     * Creates a video game with default values: empty name, current date,
     * DEFAULT platform, and DEFAULT PEGI rating.
     */
    public VideoGame() {
        this.v_name = "";
        this.v_release = LocalDate.now();
        this.v_platform = Platform.DEFAULT;
        this.v_pegi = Pegi.DEFAULT;
    }
    
    /**
     * Constructs a new VideoGame with the specified parameters.
     * The ID is automatically generated by the database.
     *
     * @param v_name The name of the video game
     * @param v_release The release date of the video game
     * @param v_platform The gaming platform
     * @param v_pegi The PEGI age rating
     */
    public VideoGame(String v_name, LocalDate v_release, Platform v_platform, Pegi v_pegi) {
        this.v_name = v_name;
        this.v_release = v_release;
        this.v_platform = v_platform;
        this.v_pegi = v_pegi;
    }

    /**
     * Constructs a new VideoGame with the specified parameters including ID.
     * Typically used when retrieving existing games from the database.
     *
     * @param v_id The unique identifier for the video game
     * @param v_name The name of the video game
     * @param v_release The release date of the video game
     * @param v_platform The gaming platform
     * @param v_pegi The PEGI age rating
     */
    public VideoGame(int v_id, String v_name, LocalDate v_release, Platform v_platform, Pegi v_pegi) {
        this.v_id = v_id;
        this.v_name = v_name;
        this.v_release = v_release;
        this.v_platform = v_platform;
        this.v_pegi = v_pegi;
    }

    /**
     * Gets the unique identifier of the video game.
     *
     * @return The video game ID
     */
    public int getV_id() {
        return v_id;
    }

    /**
     * Sets the unique identifier of the video game.
     * Note: This should generally not be called manually as the ID is auto-generated.
     *
     * @param v_id The new video game ID
     */
    public void setV_id(int v_id) {
        this.v_id = v_id;
    }

    /**
     * Gets the name of the video game.
     *
     * @return The video game name
     */
    public String getV_name() {
        return v_name;
    }

    /**
     * Sets the name of the video game.
     *
     * @param v_name The new video game name
     */
    public void setV_name(String v_name) {
        this.v_name = v_name;
    }

    /**
     * Gets the release date of the video game.
     *
     * @return The release date
     */
    public LocalDate getV_release() {
        return v_release;
    }

    /**
     * Sets the release date of the video game.
     *
     * @param v_release The new release date
     */
    public void setV_release(LocalDate v_release) {
        this.v_release = v_release;
    }

    /**
     * Gets the gaming platform of the video game.
     *
     * @return The gaming platform
     */
    public Platform getV_platform() {
        return v_platform;
    }

    /**
     * Sets the gaming platform of the video game.
     *
     * @param v_platform The new gaming platform
     */
    public void setV_platform(Platform v_platform) {
        this.v_platform = v_platform;
    }

    /**
     * Gets the PEGI rating of the video game.
     *
     * @return The PEGI rating
     */
    public Pegi getV_pegi() {
        return v_pegi;
    }

    /**
     * Sets the PEGI rating of the video game.
     *
     * @param v_pegi The new PEGI rating
     */
    public void setV_pegi(Pegi v_pegi) {
        this.v_pegi = v_pegi;
    }

    /**
     * Gets the set of listings that associate this video game with user profiles.
     *
     * @return Set of Listed objects
     */
    public Set<Listed> getListedInProfiles() {
        return listedInProfiles;
    }

    /**
     * Sets the set of listings that associate this video game with user profiles.
     *
     * @param listedInProfiles The new set of Listed objects
     */
    public void setListedInProfiles(Set<Listed> listedInProfiles) {
        this.listedInProfiles = listedInProfiles;
    }

    /**
     * Returns a string representation of the VideoGame object.
     * Includes all fields of the video game.
     *
     * @return A string representation of the VideoGame
     */
    @Override
    public String toString() {
        return "VideoGame{"
                + "v_id=" + v_id
                + ", v_name='" + v_name + '\''
                + ", v_release=" + v_release
                + ", v_platform=" + v_platform
                + ", v_pegi=" + v_pegi
                + "}";
    }
}